Repository frouriojs/frourio, pull requests merged in 2022-03, with the labels that each got.

#190 feat(validation): allow user to specify custom plainToInstance and validateOrReject
  __test__/index.spec.ts
  servers/all/$server.ts
  servers/noMulter/$server.ts
  servers/noTypedParams/$server.ts
  src/buildServerFile.ts
Labels: feature

#228 feat: add "or undefined" explicitly to support exactOptionalPropertyTypes
  CHANGELOG.md
  package.json
  servers/all/$server.ts
  servers/all/api/$api.ts
  servers/all/api/$relay.ts
  servers/all/api/500/$relay.ts
  servers/all/api/empty/$relay.ts
  servers/all/api/empty/noEmpty/$relay.ts
  servers/all/api/multiForm/$relay.ts
  servers/all/api/texts/$relay.ts
  servers/all/api/texts/_label@string/$relay.ts
  servers/all/api/texts/sample/$relay.ts
  servers/all/api/users/$relay.ts
  servers/all/api/users/_userId@number/$relay.ts
  servers/all/api/users/_userId@number/_name/$relay.ts
  servers/minimum/$server.ts
  servers/minimum/api/$api.ts
  servers/minimum/api/$relay.ts
  servers/noMulter/$server.ts
  servers/noMulter/api/$api.ts
  servers/noMulter/api/$relay.ts
  servers/noMulter/api/empty/$relay.ts
  servers/noMulter/api/empty/noEmpty/$relay.ts
  servers/noMulter/api/texts/$relay.ts
  servers/noMulter/api/texts/sample/$relay.ts
  servers/noMulter/api/users/$relay.ts
  servers/noMulter/api/users/_userId@number/$relay.ts
  servers/noTypedParams/$server.ts
  servers/noTypedParams/api/$api.ts
  servers/noTypedParams/api/$relay.ts
  servers/noTypedParams/api/empty/$relay.ts
  servers/noTypedParams/api/empty/noEmpty/$relay.ts
  servers/noTypedParams/api/multiForm/$relay.ts
  servers/noTypedParams/api/texts/$relay.ts
  servers/noTypedParams/api/texts/sample/$relay.ts
  servers/noTypedParams/api/users/$relay.ts
  servers/noValidator/$server.ts
  servers/noValidator/api/$api.ts
  servers/noValidator/api/$relay.ts
  servers/noValidator/api/empty/$relay.ts
  servers/noValidator/api/empty/noEmpty/$relay.ts
  servers/noValidator/api/multiForm/$relay.ts
  servers/noValidator/api/texts/$relay.ts
  servers/noValidator/api/texts/sample/$relay.ts
  servers/noValidator/api/users/$relay.ts
  servers/noValidator/api/users/_userId@number/$relay.ts
  src/buildServerFile.ts
  src/createControllersText.ts
  yarn.lock
Labels: documentation, chore, feature

#231 docs: update changelog
  CHANGELOG.md
Labels: documentation, chore

#233 feat: show the error when multiple path param folders made
  CHANGELOG.md
  src/createControllersText.ts
Labels: feature
