Repository frouriojs/frourio, pull requests merged in 2022-11, with the labels that each got.

#252 Fix/type error on ts48
  servers/all/$server.ts
  servers/minimum/$server.ts
  servers/noMulter/$server.ts
  servers/noTypedParams/$server.ts
  servers/noValidator/$server.ts
  src/buildServerFile.ts
Labels: bug

#253 chore: update modules
  .github/workflows/nodejs.yml
  jest.config.ts
  package.json
  servers/all/api/$api.ts
  servers/minimum/api/$api.ts
  servers/noMulter/api/$api.ts
  servers/noTypedParams/api/$api.ts
  servers/noValidator/api/$api.ts
  yarn.lock
Labels: chore

#255 release v0.29.1
  .github/workflows/nodejs.yml
  CHANGELOG.md
  package.json
Labels: documentation, chore

#257 feat: add zod validators to controller
  __test__/build.spec.ts
  __test__/index.spec.ts
  __test__/unit.spec.ts
  package.json
  servers/all/$server.ts
  servers/all/api/$api.ts
  servers/all/api/$relay.ts
  servers/all/api/500/$relay.ts
  servers/all/api/controller.ts
  servers/all/api/empty/$relay.ts
  servers/all/api/empty/noEmpty/$relay.ts
  servers/all/api/index.ts
  servers/all/api/multiForm/$relay.ts
  servers/all/api/texts/$relay.ts
  servers/all/api/texts/_label@string/$relay.ts
  servers/all/api/texts/_label@string/validators.ts
  servers/all/api/texts/sample/$relay.ts
  servers/all/api/users/$relay.ts
  servers/all/api/users/_userId@number/$relay.ts
  servers/all/api/users/_userId@number/_name/$relay.ts
  servers/all/api/users/_userId@number/_name/validators.ts
  servers/all/api/users/_userId@number/validators.ts
  servers/minimum/$server.ts
  servers/minimum/api/$relay.ts
  servers/noMulter/$server.ts
  servers/noMulter/api/$relay.ts
  servers/noMulter/api/controller.ts
  servers/noMulter/api/empty/$relay.ts
  servers/noMulter/api/empty/noEmpty/$relay.ts
  servers/noMulter/api/texts/$relay.ts
  servers/noMulter/api/texts/sample/$relay.ts
  servers/noMulter/api/users/$relay.ts
  servers/noMulter/api/users/_userId@number/$relay.ts
  servers/noMulter/api/users/_userId@number/validators.ts
  servers/noTypedParams/$server.ts
  servers/noTypedParams/api/$relay.ts
  servers/noTypedParams/api/controller.ts
  servers/noTypedParams/api/empty/$relay.ts
  servers/noTypedParams/api/empty/noEmpty/$relay.ts
  servers/noTypedParams/api/multiForm/$relay.ts
  servers/noTypedParams/api/texts/$relay.ts
  servers/noTypedParams/api/texts/sample/$relay.ts
  servers/noTypedParams/api/users/$relay.ts
  servers/noValidator/$server.ts
  servers/noValidator/api/$relay.ts
  servers/noValidator/api/controller.ts
  servers/noValidator/api/empty/$relay.ts
  servers/noValidator/api/empty/noEmpty/$relay.ts
  servers/noValidator/api/multiForm/$relay.ts
  servers/noValidator/api/texts/$relay.ts
  servers/noValidator/api/texts/sample/$relay.ts
  servers/noValidator/api/users/$relay.ts
  servers/noValidator/api/users/_userId@number/$relay.ts
  servers/noValidator/api/users/_userId@number/validators.ts
  servers/noValidator/api/users/controller.ts
  src/buildServerFile.ts
  src/createControllersText.ts
  src/createDefaultFilesIfNotExists.ts
  yarn.lock
Labels: feature

#258 chore: release v0.30.0
  CHANGELOG.md
Labels: documentation, chore

#259 fix: type definitions of $server.ts
  CHANGELOG.md
  servers/all/$server.ts
  servers/minimum/$server.ts
  servers/noMulter/$server.ts
  servers/noTypedParams/$server.ts
  servers/noValidator/$server.ts
  src/buildServerFile.ts
  src/createControllersText.ts
Labels: bug, documentation, chore

#261 fix: use safeParse for validation error
  CHANGELOG.md
  __test__/index.spec.ts
  servers/all/$server.ts
  servers/minimum/$server.ts
  servers/noMulter/$server.ts
  servers/noValidator/$server.ts
  src/buildServerFile.ts
Labels: bug, documentation, chore

#262 feat: add response schema and hooks to controller
  .github/workflows/nodejs.yml
  CHANGELOG.md
  README.md
  __test__/index.spec.ts
  jest.config.ts
  package.json
  servers/all/$server.ts
  servers/all/api/$relay.ts
  servers/all/api/500/$relay.ts
  servers/all/api/controller.ts
  servers/all/api/empty/$relay.ts
  servers/all/api/empty/noEmpty/$relay.ts
  servers/all/api/multiForm/$relay.ts
  servers/all/api/texts/$relay.ts
  servers/all/api/texts/_label@string/$relay.ts
  servers/all/api/texts/sample/$relay.ts
  servers/all/api/users/$relay.ts
  servers/all/api/users/_userId@number/$relay.ts
  servers/all/api/users/_userId@number/_name/$relay.ts
  servers/minimum/$server.ts
  servers/minimum/api/$relay.ts
  servers/noMulter/$server.ts
  servers/noMulter/api/$relay.ts
  servers/noMulter/api/empty/$relay.ts
  servers/noMulter/api/empty/noEmpty/$relay.ts
  servers/noMulter/api/texts/$relay.ts
  servers/noMulter/api/texts/sample/$relay.ts
  servers/noMulter/api/users/$relay.ts
  servers/noMulter/api/users/_userId@number/$relay.ts
  servers/noTypedParams/$server.ts
  servers/noTypedParams/api/$relay.ts
  servers/noTypedParams/api/empty/$relay.ts
  servers/noTypedParams/api/empty/noEmpty/$relay.ts
  servers/noTypedParams/api/multiForm/$relay.ts
  servers/noTypedParams/api/texts/$relay.ts
  servers/noTypedParams/api/texts/sample/$relay.ts
  servers/noTypedParams/api/users/$relay.ts
  servers/noValidator/$server.ts
  servers/noValidator/api/$relay.ts
  servers/noValidator/api/empty/$relay.ts
  servers/noValidator/api/empty/noEmpty/$relay.ts
  servers/noValidator/api/multiForm/$relay.ts
  servers/noValidator/api/texts/$relay.ts
  servers/noValidator/api/texts/sample/$relay.ts
  servers/noValidator/api/users/$relay.ts
  servers/noValidator/api/users/_userId@number/$relay.ts
  src/buildServerFile.ts
  src/createControllersText.ts
  yarn.lock
Labels: documentation, chore, feature
